/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.projetolpooe1_nicolasscopel.view;

import br.edu.ifsul.cc.lpoo.projetolpooe1_nicolasscopel.dao.PersistenciaJPA;
import br.edu.ifsul.cc.lpoo.projetolpooe1_nicolasscopel.model.Locacao;
import br.edu.ifsul.cc.lpoo.projetolpooe1_nicolasscopel.model.Veiculo;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas Scopel
 */
public class TelaCadastroLocacao extends javax.swing.JFrame {
    
    DefaultListModel<Locacao> mascaraItemLista = new DefaultListModel<>();
    

    /**
     * Creates new form TelaCadastroLocacao
     */
    public TelaCadastroLocacao() {
        
        initComponents();
        lstLocacoes.clearSelection();
        lstLocacoes.setModel(mascaraItemLista);
        listarLocacoes();
    }
    
    
    private void listarLocacoes() {

        PersistenciaJPA jpa = new PersistenciaJPA();
        jpa.conexaoAberta();

        List<Locacao> locacoes = jpa.getLocacoes();
        mascaraItemLista.clear();

        for (Locacao loc : locacoes) {
            mascaraItemLista.addElement(loc);

        }
        lstLocacoes.setModel(mascaraItemLista);
        jpa.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaLocacaoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLocacoes = new javax.swing.JList<>();
        btnNovaLocacao = new javax.swing.JButton();
        btnEditarLocacao = new javax.swing.JButton();
        btnExcluirLocacao = new javax.swing.JButton();
        btnCancelarLocacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TELA CADASTRO LOCAÇÃO");

        jLabel2.setText("Pesquisar Locação via Nome:");

        txtBuscaLocacaoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaLocacaoNomeKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("LISTA DE LOCAÇÕES");

        jScrollPane1.setViewportView(lstLocacoes);

        btnNovaLocacao.setText("Nova");
        btnNovaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaLocacaoActionPerformed(evt);
            }
        });

        btnEditarLocacao.setText("Editar");
        btnEditarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLocacaoActionPerformed(evt);
            }
        });

        btnExcluirLocacao.setText("Excluir");
        btnExcluirLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLocacaoActionPerformed(evt);
            }
        });

        btnCancelarLocacao.setText("Cancelar");
        btnCancelarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscaLocacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNovaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnExcluirLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnCancelarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscaLocacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovaLocacao)
                    .addComponent(btnEditarLocacao)
                    .addComponent(btnExcluirLocacao)
                    .addComponent(btnCancelarLocacao))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLocacaoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarLocacaoActionPerformed

    private void btnNovaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaLocacaoActionPerformed
        TelaNovoLocacao novo = new TelaNovoLocacao(this, true);
        novo.setVisible(true);
        
        listarLocacoes();
    }//GEN-LAST:event_btnNovaLocacaoActionPerformed

    private void txtBuscaLocacaoNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaLocacaoNomeKeyReleased
       // TODO add your handling code here:
        String textoBusca = txtBuscaLocacaoNome.getText().trim();
        
        if(textoBusca.isEmpty()){
            //return;
        }
                
        PersistenciaJPA jpa = new PersistenciaJPA();
        jpa.conexaoAberta();

        List<Locacao> locacoes = jpa.getLocacoes(textoBusca);
        mascaraItemLista.clear();

        for (Locacao loc : locacoes) {
            mascaraItemLista.addElement(loc);

        }
        lstLocacoes.setModel(mascaraItemLista);
        jpa.fecharConexao();
    }//GEN-LAST:event_txtBuscaLocacaoNomeKeyReleased

    private void btnEditarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLocacaoActionPerformed
       
        Locacao locacaoSelecionada = lstLocacoes.getSelectedValue();
        
        if(locacaoSelecionada != null){
            TelaEditarLocacao editar = new TelaEditarLocacao(this, true);
            editar.setLocacao(locacaoSelecionada);
            editar.setVisible(true);
            listarLocacoes();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhuma Locacao Selecionada");
            
        }
        
    }//GEN-LAST:event_btnEditarLocacaoActionPerformed

    private void btnExcluirLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLocacaoActionPerformed
        // TODO add your handling code here:
        Locacao locacaoSelecionada = lstLocacoes.getSelectedValue();
        PersistenciaJPA jpa = new PersistenciaJPA();
        
        if(locacaoSelecionada != null){
            int confirmPanel = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover o veiculo " + locacaoSelecionada + " ?");

        if (confirmPanel == JOptionPane.YES_OPTION) {

            try {

                jpa.conexaoAberta();
                jpa.remover(locacaoSelecionada);
                jpa.fecharConexao();
                listarLocacoes();
            } catch (Exception ex) {
                System.out.println("Erro ao remover locacao selecionado!");

            } finally {
                jpa.fecharConexao();
            }
        }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhuma locacao selecionado! ");
        }
    }//GEN-LAST:event_btnExcluirLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLocacao;
    private javax.swing.JButton btnEditarLocacao;
    private javax.swing.JButton btnExcluirLocacao;
    private javax.swing.JButton btnNovaLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Locacao> lstLocacoes;
    private javax.swing.JTextField txtBuscaLocacaoNome;
    // End of variables declaration//GEN-END:variables
}
